
###
////////////////////////////////////////////////////////////////////Products
//REST Testing

//Inventory
GET http://localhost:5000/product

###
GET http://localhost:5000/product/673f30ab5a93805ed3dd93bc

###
POST http://localhost:5000/product
Content-Type: application/json

{
    "item": "Item 3",
    "price": 99.00
}

###
DELETE http://localhost:5000/product/674098d62da2ced83aba8277

###
//use this with a button to update ordered from false to true. Like "BUY" button
PATCH http://localhost:5000/product/673f30ab5a93805ed3dd93bc
Content-Type: application/json

{
    "ordered": true
}

