

//Inventory
GET http://localhost:3000/inventory

###
GET http://localhost:3000/inventory/673b294c60f8cb4b2b5fec52

###
POST http://localhost:3000/inventory
Content-Type: application/json

{
    "item": "Coming soon",
    "price": 99.00
}

###
DELETE http://localhost:3000/inventory/673b29dd60f8cb4b2b5fec62

###
//use this with a button to update ordered from false to true. Like "BUY" button
PATCH http://localhost:3000/inventory/673b290060f8cb4b2b5fec4f
Content-Type: application/json

{
    "ordered": false
}

