
###
////////////////////////////////////////////////////////////////////Products
//REST Testing

//Inventory
GET http://localhost:5000/product

###
GET http://localhost:5000/product/673f30ab5a93805ed3dd93bc

###
POST http://localhost:5000/product
Content-Type: application/json

{
    "item": "Item 5",
    "price": 99.00,
    "category": "Perfumes" 
}

###
DELETE http://localhost:5000/product/6745cfb600bed70e67b65047

###
//use this with a button to update ordered from false to true. Like "BUY" button
PATCH http://localhost:5000/product/6740d1aee43b451e045d5161/toggleOrder
Content-Type: application/json


